---
title: "simple-shiny-ebonylz"
author: "ebonylz"
date: "2025-03-04"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse, stringr)
```

## Introduction

This R Markdown document is made interactive using Shiny to demonstrate my abilities to make interactive data visualizations.

```{r load data, include=FALSE}
title <- read_tsv('title.basics.tsv')
ratings <- read_tsv('title.ratings.tsv')

film <- title %>%
  merge(ratings) %>%
  filter(numVotes > 100) %>%
  mutate(startYear = as.Date(as.character(startYear), format = "%Y"),
         endYear= as.Date(as.character(endYear), format = "%Y"))
rm(ratings, title)
gc()

```

## IMDb data{.tabset}

### Top movies by year

The plot below shows time series of movies with an average rating higher than an 8 by more than 1,000 raters.

```{r top movies, echo=FALSE}
inputPanel(
  selectInput("filmtype", label = "Type of film: ",
              choices = unique(film$titleType), 
              selected = "movie", 
              multiple = TRUE),
  sliderInput("daterange",
              label = "Date Range: ",
              min = 1890,
              max = 2025,
              value = 
                c(2019, 2025),
              sep = "")
)

renderPlot({
  film %>%
    filter(titleType %in% input$filmtype) %>%
    filter(averageRating >= 8 & 
             numVotes >= 1000 &
             startYear >= as.Date(as.character(input$daterange[1]), format = "%Y") &
             startYear <= as.Date(as.character(input$daterange[2]), format = "%Y")
           ) %>%
    ggplot(aes(x = startYear, y = averageRating)) +
    geom_point(aes(size = numVotes, color = titleType)) +
    geom_text(data = .%>% group_by(startYear) %>% slice_max(order_by = numVotes, n = 3),
              mapping = aes(x=startYear, y = averageRating, label = originalTitle, size = numVotes), check_overlap = TRUE, position = position_dodge(0.9)
              ) +
      labs(x = NULL, y = NULL,
           title = "Ratings with an 8 or higher",
           subtitle = paste0("Date Range: ",
                             input$daterange[1],
                             " to ",
                             input$daterange[2], "."
                             ),
           caption = "Source: IMDb") +
    scale_x_date() +
    scale_size_continuous(labels = scales::unit_format(
      unit = "k",
      scale = 1e-3,
      accuracy = 1,
      sep = ""
      #round = 4
    ), name = 'Votes') +
    scale_color_discrete(name = 'Media') +
    theme_minimal() +
    theme(
      legend.position = "top"
    )
})
 
```
